# Generated by Django 5.2.5 on 2025-10-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
