# Generated by Django 5.2.5 on 2025-10-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundstransfer',
            name='reference_code',
            field=models.CharField(default='undefined', max_length=50, unique=True),
        ),
    ]
