# Generated by Django 5.2.5 on 2025-09-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_adminprofile_user_alter_clientprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrator')], default='client', max_length=20),
        ),
    ]
