# Generated by Django 5.2.5 on 2025-10-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth0_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
