# Generated by Django 5.2.5 on 2025-10-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_auth0_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_ip',
        ),
    ]
